AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Create MWAA environment and Airflow bucket.
Parameters:
  ProjectName:
    Description: Project name that is prefixed to resource names
    Type: String
  EnvironmentName:
    Description: Environment name (e.g., Development, Test, Production)
    Type: String
  EnviromentOwner:
    Description: Owner of Enviroment (e.g., Data Analysts, Marketing, Finance)
    Type: String
  ExecutionRole:
    Description: MWAA exection role
    Type: String
  AirflowEnvironmentName:
    Description: Name of the MWAA environment
    Type: String
  AirflowVersion:
    Description: MWAA Airflow version
    Type: String
  EnvironmentClass:
    Description: MWAA Environment class
    Type: String
  SecurityGroupOne:
    Description: Security group
    Type: String
  SubnetOne:
    Description: First of two private subnets
    Type: String
  SubnetTwo:
    Description: Second of two private subnets
    Type: String
  WebserverAccessMode:
    Description: Public or private access?
    Type: String
  WeeklyMaintenanceWindowStart:
    Description: Weekly maintenance window start
    Type: String
  WebserverUrl:
    Description: Airflow UI URL
    Type: String
Resources:
  AirflowBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ '-', [ 'airflow', !Ref 'AWS::AccountId', !Ref 'AWS::Region' ] ]
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Ref ProjectName
  MwaaExecutionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: MWAA_EMR_Policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:GetObject'
              - 'elasticmapreduce:DescribeStep'
              - 'elasticmapreduce:AddJobFlowSteps'
              - 'elasticmapreduce:RunJobFlow'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'iam:PassRole'
            Resource:
              - !Join [ '', [ 'arn:aws:iam::', !Ref 'AWS::AccountId', ':role/EMR_DemoRole' ] ]
              - !Join [ '', [ 'arn:aws:iam::', !Ref 'AWS::AccountId', ':role/EMR_EC2_DemoRole' ] ]
              - !Join [ '', [ 'arn:aws:iam::', !Ref 'AWS::AccountId', ':role/EMR_EC2_DefaultRole' ] ]
              - !Join [ '', [ 'arn:aws:iam::', !Ref 'AWS::AccountId', ':role/EMR_DefaultRole' ] ]
  DevelopmentEnvironment:
    Type: AWS::MWAA::Environment
    Properties:
      #      AirflowConfigurationOptions:
      AirflowVersion: !Ref AirflowVersion
      DagS3Path: 'dags'
      EnvironmentClass: !Ref EnvironmentClass
      ExecutionRoleArn: !Join [ '', [ 'arn:aws:iam::', !Ref 'AWS::AccountId', ':role/service-role/', !Ref ExecutionRole ] ]
      #      KmsKey: String
      LoggingConfiguration:
        DagProcessingLogs:
          CloudWatchLogGroupArn: !Join [ '', [ 'arn:aws:logs::', !Ref 'AWS::AccountId', ':log-group:airflow-', !Ref AirflowEnvironmentName, '-DagProcessing' ] ]
            Enabled: true
            LogLevel: 'WARNING'
        SchedulerLogs:
          CloudWatchLogGroupArn: !Join [ '', [ 'arn:aws:logs::', !Ref 'AWS::AccountId', ':log-group:airflow-', !Ref AirflowEnvironmentName, '-Scheduler' ] ]
            Enabled: true
            LogLevel: 'WARNING'
        TaskLogs:
          CloudWatchLogGroupArn: !Join [ '', [ 'arn:aws:logs::', !Ref 'AWS::AccountId', ':log-group:airflow-', !Ref AirflowEnvironmentName, '-Task' ] ]
            Enabled: true
            LogLevel: 'WARNING'
        WebserverLogs:
          CloudWatchLogGroupArn: !Join [ '', [ 'arn:aws:logs::', !Ref 'AWS::AccountId', ':log-group:airflow-', !Ref AirflowEnvironmentName, '-Webserver' ] ]
            Enabled: true
            LogLevel: 'WARNING'
        WorkerLogs:
          CloudWatchLogGroupArn: !Join [ '', [ 'arn:aws:logs::', !Ref 'AWS::AccountId', ':log-group:airflow-', !Ref AirflowEnvironmentName, '-Worker' ] ]
            Enabled: true
            LogLevel: 'WARNING'
      MaxWorkers: 10
      NetworkConfiguration:
        SecurityGroupIds:
          SecurityGroupList:
            - !Ref SecurityGroupOne
        SubnetIds:
          SubnetList:
            - !Ref SubnetOne
            - !Ref SubnetTwo
      #      PluginsS3ObjectVersion: String
      #      PluginsS3Path: String
      #      RequirementsS3ObjectVersion: String
      #      RequirementsS3Path: String
      SourceBucketArn: !Join [ '', [ 'arn:aws:s3:::', !Ref AirflowBucket ] ]
      Tags:
        - Key: Name
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Owner
          Value: !Ref EnviromentOwner
      WebserverAccessMode: !Ref WebserverAccessMode
      WebserverUrl: !Ref WebserverUrl
      WeeklyMaintenanceWindowStart: !Ref WeeklyMaintenanceWindowStart
  AirflowBucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/emr_demo/airflow_bucket'
      Type: String
      Value: !Ref AirflowBucket
      Description: MWAA (Airflow) bucket name
      Tags:
        Environment: !Ref EnvironmentName
